### ISSUE TITLE
urllib3 + ssl warning when attempting to run

### ISSUE THREAD

**Issue by rmanly** [g-aggarwal/mlx-hub#27]
```
5:23:13 % mlx-hub-cli --start
/Users/ryan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

An error occurred: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by g-aggarwal** [comment]
@rmanly Thanks for report this. Based on [this thread](https://github.com/urllib3/urllib3/issues/3020), it sounds like the issue is with the python version preinstalled with macOS. I just tested it with python 3.12 installed from homebrew and I don't see the warning. Can you confirm which python version are you using and how it was installed? Thanks!

**Comment by rmanly** [comment]
Sorry for the delay.

Newer Python and a correct $PATH did the trick.

Thanks!
